import React, { useState } from 'react';
import { ShoppingBag, Trash2, Share2, CheckCircle, Copy, AlertCircle } from 'lucide-react';

export default function PurchaseList({ purchaseData, onDeleteItem, onClearList }) {
  const { items, total_cost, item_count } = purchaseData;
  const [copied, setCopied] = useState(false);

  // Generate clean WhatsApp message format for distributors
  const generateWhatsAppMessage = () => {
    let msg = `🛒 *KIRANA STORE PURCHASE ORDER*\n`;
    msg += `Store: Gupta Kirana Store, Lucknow\n`;
    msg += `Date: ${new Date().toLocaleDateString('en-IN')}\n`;
    msg += `-----------------------------------\n`;
    items.forEach((item, idx) => {
      msg += `${idx + 1}. *${item.product_name}* - ${item.quantity} ${item.unit} (₹${item.estimated_cost})\n`;
    });
    msg += `-----------------------------------\n`;
    msg += `*Estimated Total: ₹${total_cost.toLocaleString('en-IN')}*\n`;
    msg += `Generated by KiranaMitra AI 🤖`;
    return msg;
  };

  const handleCopyWhatsApp = () => {
    const text = generateWhatsAppMessage();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="glass-panel p-5">
      
      {/* Header */}
      <div className="flex items-center justify-between mb-4 pb-3 border-b border-gray-800">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-amber-500/20 border border-amber-500/40 flex items-center justify-center">
            <ShoppingBag className="w-4 h-4 text-amber-400" />
          </div>
          <div>
            <h2 className="text-base font-bold text-gray-100 flex items-center gap-2">
              🛒 Smart Purchase List
              <span className="bg-amber-500/20 text-amber-300 text-xs px-2 py-0.5 rounded-full font-mono font-bold">
                {item_count} Items
              </span>
            </h2>
            <p className="text-xs text-gray-400">AI-generated purchase order for wholesalers & distributors</p>
          </div>
        </div>

        {items.length > 0 && (
          <button
            onClick={onClearList}
            className="text-xs text-gray-400 hover:text-red-400 flex items-center gap-1 transition-all cursor-pointer"
            title="Clear Purchase List"
          >
            <Trash2 className="w-3.5 h-3.5" /> Clear All
          </button>
        )}
      </div>

      {/* Items Table / List */}
      {items.length === 0 ? (
        <div className="py-8 text-center bg-gray-950/60 rounded-xl border border-gray-800">
          <ShoppingBag className="w-8 h-8 text-gray-600 mx-auto mb-2" />
          <p className="text-xs text-gray-400">Purchase list is empty.</p>
          <p className="text-[11px] text-gray-500 mt-1">
            Say e.g. <strong className="text-amber-400">"Bhai Maggi ke 20 packet aur 5 kilo chini order mein daal de"</strong> to auto-populate!
          </p>
        </div>
      ) : (
        <div className="space-y-2.5 max-h-[350px] overflow-y-auto pr-1">
          {items.map((item) => (
            <div
              key={item.id}
              className="p-3 rounded-xl bg-gray-950 border border-gray-800 hover:border-gray-700 flex items-center justify-between gap-3 transition-all"
            >
              <div className="flex items-center gap-3">
                <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 text-xs font-bold flex items-center justify-center shrink-0">
                  ✓
                </span>
                <div>
                  <h4 className="text-xs font-bold text-gray-100">{item.product_name}</h4>
                  <span className="text-[11px] text-gray-400">
                    Supplier: {item.supplier}
                  </span>
                </div>
              </div>

              <div className="flex items-center gap-4">
                <div className="text-right">
                  <span className="text-sm font-extrabold text-amber-400 block">
                    {item.quantity} {item.unit}
                  </span>
                  <span className="text-[11px] text-gray-400">
                    Est: ₹{item.estimated_cost}
                  </span>
                </div>

                <button
                  onClick={() => onDeleteItem(item.id)}
                  className="w-7 h-7 bg-gray-900 hover:bg-red-500/20 text-gray-400 hover:text-red-400 rounded-lg flex items-center justify-center transition-all cursor-pointer"
                  title="Remove Item"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>

            </div>
          ))}
        </div>
      )}

      {/* Summary Footer & WhatsApp Export */}
      {items.length > 0 && (
        <div className="mt-4 pt-3 border-t border-gray-800">
          <div className="flex items-center justify-between mb-3 bg-amber-500/10 p-3 rounded-xl border border-amber-500/30">
            <span className="text-xs font-bold text-gray-300">Estimated Total Order Cost:</span>
            <span className="text-lg font-black text-amber-400">₹{total_cost.toLocaleString('en-IN')}</span>
          </div>

          <button
            onClick={handleCopyWhatsApp}
            className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-extrabold text-xs py-2.5 rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-600/20 cursor-pointer"
          >
            {copied ? (
              <>
                <CheckCircle className="w-4 h-4 text-white" /> Order Copied to Clipboard!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" /> Copy WhatsApp Order Format for Distributor
              </>
            )}
          </button>
        </div>
      )}

    </div>
  );
}
